# Generated by Django 4.1 on 2022-08-24 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_patient', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('name_doctor', models.CharField(max_length=100)),
            ],
        ),
    ]
